experiment_name: distilbert_main
run_name: null

device: cpu
# num_labels: 442
tags: ['2D', 'RPG', 'Multiplayer', 'Simulation', 'Puzzle', 'Atmospheric',
       'Great Soundtrack', 'Story Rich', 'Sci-fi', 'Shooter', 'Funny',
       'First-Person', 'Fantasy', 'Difficult', 'Platformer',
       'Female Protagonist', 'Open World', 'Co-op', 'Horror', 'Pixel Graphics',
       'Retro', 'Free to Play', 'Arcade', 'FPS', 'Classic', 'Point & Click',
       'Comedy', 'Anime', 'Exploration', 'Early Access', 'Cute', 'Turn-Based',
       'Family Friendly', 'Sandbox', 'Survival', 'VR', 'Space', 'Third Person',
       'Gore', 'Controller', 'Tactical', 'Turn-Based Strategy', 'Colorful',
       'Psychological Horror', 'Mystery', 'Choices Matter',
       'Local Multiplayer', 'Local Co-Op', 'Side Scroller', 'RTS',
       'Shoot ''Em Up', 'Massively Multiplayer', 'Online Co-Op', 'Visual Novel',
       'Violent', 'Racing', 'Zombies', 'War', 'Top-Down', 'Sports', 'Physics',
       'Historical', 'Nudity', 'Action RPG', 'Dark', 'JRPG', 'Isometric',
       'Puzzle Platformer', 'PvP', 'Management', 'Building', 'Short',
       'Tower Defense', 'Character Customization', 'Hidden Object', '3D',
       'Replay Value', 'Walking Simulator', '1990''s', 'Procedural Generation',
       'Cartoony', 'Roguelike', 'Turn-Based Combat', 'Memes', 'Hack and Slash',
       'Military', 'Post-apocalyptic', 'Crafting', 'RPGMaker', 'Fast-Paced',
       'Survival Horror', 'Action-Adventure', 'Bullet Hell', 'Futuristic',
       'Relaxing', 'Realistic', 'Moddable']
model_name: distilbert-base-uncased
batch_size: 8
threshold: 0.5
max_epochs: 10

p_train_samples: 0.6
random_seed: 42